# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value



services:

    Core:
        class:     DmarcDash\Core
        arguments: [ @kernel, @service_container, @doctrine.orm.entity_manager ]

    ModelRepositoryService:
        class:     DmarcDash\ModelRepositoryService
        arguments: [ @Core, @doctrine.orm.entity_manager ]

    EntityRepositoryService:
        class:     DmarcDash\EntityRepositoryService
        arguments: [ @Core, @doctrine.orm.entity_manager ]


    Chart:
        class:     DmarcDash\Service\ChartService
        arguments: [ @Core, @doctrine.orm.entity_manager ]
    Stats:
        class:     DmarcDash\Service\StatsService
        arguments: [ @Core, @doctrine.orm.entity_manager ]



    ### Model repositories
    #
    ModelRepository_Domain:
        class:     DmarcDash\ModelRepository\DomainModelRepository
        arguments: [ @Core, @doctrine.orm.entity_manager ]

    ModelRepository_Report:
        class:     DmarcDash\ModelRepository\ReportModelRepository
        arguments: [ @Core, @doctrine.orm.entity_manager ]

    ModelRepository_ReportRecord:
        class:     DmarcDash\ModelRepository\ReportRecordModelRepository
        arguments: [ @Core, @doctrine.orm.entity_manager ]

    ModelRepository_User:
        class:     DmarcDash\ModelRepository\UserModelRepository
        arguments: [ @Core, @doctrine.orm.entity_manager ]
